// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateAlert = `-- name: ActivateAlert :one
UPDATE alerts
SET status = 'active', updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, metric, operator, value, ca, repeatable, cooldown_seconds, status, updated_at, created_at
`

type ActivateAlertParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"userId"`
}

func (q *Queries) ActivateAlert(ctx context.Context, arg ActivateAlertParams) (*Alert, error) {
	row := q.db.QueryRow(ctx, activateAlert, arg.ID, arg.UserID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.Operator,
		&i.Value,
		&i.Ca,
		&i.Repeatable,
		&i.CooldownSeconds,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (
    id, user_id, metric, operator, value, ca, repeatable, cooldown_seconds, status
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, metric, operator, value, ca, repeatable, cooldown_seconds, status, updated_at, created_at
`

type CreateAlertParams struct {
	UserID          string         `json:"userId"`
	Metric          string         `binding:"required" json:"metric"`
	Operator        string         `binding:"required" json:"operator"`
	Value           pgtype.Numeric `binding:"required" json:"value"`
	Ca              string         `binding:"required" example:"SP1Y5YSTAHZ88XYK1VPDH24GY0HPX5J4JECTMY4A1.velar-token" json:"ca"`
	Repeatable      bool           `binding:"required" json:"repeatable"`
	CooldownSeconds int32          `json:"cooldownSeconds"`
	Status          string         `binding:"required" json:"status"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (*Alert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.UserID,
		arg.Metric,
		arg.Operator,
		arg.Value,
		arg.Ca,
		arg.Repeatable,
		arg.CooldownSeconds,
		arg.Status,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.Operator,
		&i.Value,
		&i.Ca,
		&i.Repeatable,
		&i.CooldownSeconds,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteAlert = `-- name: DeleteAlert :exec
DELETE FROM alerts
WHERE id = $1 AND user_id = $2
`

type DeleteAlertParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"userId"`
}

func (q *Queries) DeleteAlert(ctx context.Context, arg DeleteAlertParams) error {
	_, err := q.db.Exec(ctx, deleteAlert, arg.ID, arg.UserID)
	return err
}

const getActiveAlertsByMetric = `-- name: GetActiveAlertsByMetric :many
SELECT id, user_id, metric, operator, value, ca, repeatable, cooldown_seconds, status, updated_at, created_at FROM alerts
WHERE metric = $1 AND status = 'active'
`

func (q *Queries) GetActiveAlertsByMetric(ctx context.Context, metric string) ([]*Alert, error) {
	rows, err := q.db.Query(ctx, getActiveAlertsByMetric, metric)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Metric,
			&i.Operator,
			&i.Value,
			&i.Ca,
			&i.Repeatable,
			&i.CooldownSeconds,
			&i.Status,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlertById = `-- name: GetAlertById :one
SELECT id, user_id, metric, operator, value, ca, repeatable, cooldown_seconds, status, updated_at, created_at FROM alerts
WHERE id = $1 AND user_id = $2
`

type GetAlertByIdParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"userId"`
}

func (q *Queries) GetAlertById(ctx context.Context, arg GetAlertByIdParams) (*Alert, error) {
	row := q.db.QueryRow(ctx, getAlertById, arg.ID, arg.UserID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.Operator,
		&i.Value,
		&i.Ca,
		&i.Repeatable,
		&i.CooldownSeconds,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getAlertsByUserId = `-- name: GetAlertsByUserId :many
SELECT id, user_id, metric, operator, value, ca, repeatable, cooldown_seconds, status, updated_at, created_at FROM alerts
WHERE user_id = $1
`

func (q *Queries) GetAlertsByUserId(ctx context.Context, userID string) ([]*Alert, error) {
	rows, err := q.db.Query(ctx, getAlertsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Metric,
			&i.Operator,
			&i.Value,
			&i.Ca,
			&i.Repeatable,
			&i.CooldownSeconds,
			&i.Status,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasAlert = `-- name: HasAlert :one
SELECT EXISTS (
    SELECT 1 FROM alerts
    WHERE id = $1 AND user_id = $2
)
`

type HasAlertParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"userId"`
}

func (q *Queries) HasAlert(ctx context.Context, arg HasAlertParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAlert, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const pauseAlert = `-- name: PauseAlert :one
UPDATE alerts
SET status = 'paused', updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, metric, operator, value, ca, repeatable, cooldown_seconds, status, updated_at, created_at
`

type PauseAlertParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"userId"`
}

func (q *Queries) PauseAlert(ctx context.Context, arg PauseAlertParams) (*Alert, error) {
	row := q.db.QueryRow(ctx, pauseAlert, arg.ID, arg.UserID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.Operator,
		&i.Value,
		&i.Ca,
		&i.Repeatable,
		&i.CooldownSeconds,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const triggerAlert = `-- name: TriggerAlert :one
UPDATE alerts
SET status = 'triggered', updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, metric, operator, value, ca, repeatable, cooldown_seconds, status, updated_at, created_at
`

type TriggerAlertParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"userId"`
}

func (q *Queries) TriggerAlert(ctx context.Context, arg TriggerAlertParams) (*Alert, error) {
	row := q.db.QueryRow(ctx, triggerAlert, arg.ID, arg.UserID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.Operator,
		&i.Value,
		&i.Ca,
		&i.Repeatable,
		&i.CooldownSeconds,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const updateAlert = `-- name: UpdateAlert :one
UPDATE alerts
SET metric = $3,
    operator = $4,
    value = $5,
    ca = $6,
    repeatable = $7,
    cooldown_seconds = $8,
    status = $9,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, metric, operator, value, ca, repeatable, cooldown_seconds, status, updated_at, created_at
`

type UpdateAlertParams struct {
	ID              uuid.UUID      `json:"id"`
	UserID          string         `json:"userId"`
	Metric          string         `binding:"required" json:"metric"`
	Operator        string         `binding:"required" json:"operator"`
	Value           pgtype.Numeric `binding:"required" json:"value"`
	Ca              string         `binding:"required" example:"SP1Y5YSTAHZ88XYK1VPDH24GY0HPX5J4JECTMY4A1.velar-token" json:"ca"`
	Repeatable      bool           `binding:"required" json:"repeatable"`
	CooldownSeconds int32          `json:"cooldownSeconds"`
	Status          string         `binding:"required" json:"status"`
}

func (q *Queries) UpdateAlert(ctx context.Context, arg UpdateAlertParams) (*Alert, error) {
	row := q.db.QueryRow(ctx, updateAlert,
		arg.ID,
		arg.UserID,
		arg.Metric,
		arg.Operator,
		arg.Value,
		arg.Ca,
		arg.Repeatable,
		arg.CooldownSeconds,
		arg.Status,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.Operator,
		&i.Value,
		&i.Ca,
		&i.Repeatable,
		&i.CooldownSeconds,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}
