// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (
    user_id, metric, operator, value, ca, repeatable, status
) VALUES (
    $1, $2, $3, $4, $5, $6, 'active'
)
RETURNING id, user_id, metric, operator, value, ca, repeatable, status, updated_at, created_at
`

type CreateAlertParams struct {
	UserID     string `json:"userId"`
	Metric     string `binding:"required" json:"metric"`
	Operator   string `binding:"required" json:"operator"`
	Value      string `binding:"required" json:"value"`
	Ca         string `binding:"required" example:"SP1Y5YSTAHZ88XYK1VPDH24GY0HPX5J4JECTMY4A1.velar-token" json:"ca"`
	Repeatable bool   `binding:"required" json:"repeatable"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (*Alert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.UserID,
		arg.Metric,
		arg.Operator,
		arg.Value,
		arg.Ca,
		arg.Repeatable,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.Operator,
		&i.Value,
		&i.Ca,
		&i.Repeatable,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const createAlertChannel = `-- name: CreateAlertChannel :exec
INSERT INTO alert_channels (alert_id, channel_id)
VALUES ($1, $2)
ON CONFLICT (alert_id, channel_id) DO NOTHING
`

type CreateAlertChannelParams struct {
	AlertID   uuid.UUID `json:"alertId"`
	ChannelID uuid.UUID `json:"channelId"`
}

func (q *Queries) CreateAlertChannel(ctx context.Context, arg CreateAlertChannelParams) error {
	_, err := q.db.Exec(ctx, createAlertChannel, arg.AlertID, arg.ChannelID)
	return err
}

const createAlertChannels = `-- name: CreateAlertChannels :exec
INSERT INTO alert_channels (alert_id, channel_id)
SELECT $1, UNNEST($2::uuid[])
ON CONFLICT (alert_id, channel_id) DO NOTHING
`

type CreateAlertChannelsParams struct {
	AlertID uuid.UUID   `json:"alertId"`
	Column2 []uuid.UUID `json:"column2"`
}

func (q *Queries) CreateAlertChannels(ctx context.Context, arg CreateAlertChannelsParams) error {
	_, err := q.db.Exec(ctx, createAlertChannels, arg.AlertID, arg.Column2)
	return err
}

const deleteAlert = `-- name: DeleteAlert :one
DELETE FROM alerts
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, metric, operator, value, ca, repeatable, status, updated_at, created_at
`

type DeleteAlertParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"userId"`
}

func (q *Queries) DeleteAlert(ctx context.Context, arg DeleteAlertParams) (*Alert, error) {
	row := q.db.QueryRow(ctx, deleteAlert, arg.ID, arg.UserID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.Operator,
		&i.Value,
		&i.Ca,
		&i.Repeatable,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteAlertChannels = `-- name: DeleteAlertChannels :exec
DELETE FROM alert_channels WHERE alert_id = $1
`

func (q *Queries) DeleteAlertChannels(ctx context.Context, alertID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlertChannels, alertID)
	return err
}

const deleteAllInactiveAlerts = `-- name: DeleteAllInactiveAlerts :exec
DELETE FROM alerts
WHERE user_id = $1
  AND status != 'active'
`

func (q *Queries) DeleteAllInactiveAlerts(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAllInactiveAlerts, userID)
	return err
}

const getActiveAlertsByMetric = `-- name: GetActiveAlertsByMetric :many
SELECT id, user_id, metric, operator, value, ca, repeatable, status, updated_at, created_at FROM alerts
WHERE metric = $1 AND status = 'active'
`

func (q *Queries) GetActiveAlertsByMetric(ctx context.Context, metric string) ([]*Alert, error) {
	rows, err := q.db.Query(ctx, getActiveAlertsByMetric, metric)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Metric,
			&i.Operator,
			&i.Value,
			&i.Ca,
			&i.Repeatable,
			&i.Status,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlertById = `-- name: GetAlertById :one
SELECT id, user_id, metric, operator, value, ca, repeatable, status, updated_at, created_at FROM alerts
WHERE id = $1 AND user_id = $2
`

type GetAlertByIdParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"userId"`
}

func (q *Queries) GetAlertById(ctx context.Context, arg GetAlertByIdParams) (*Alert, error) {
	row := q.db.QueryRow(ctx, getAlertById, arg.ID, arg.UserID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.Operator,
		&i.Value,
		&i.Ca,
		&i.Repeatable,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getAllChannels = `-- name: GetAllChannels :many
SELECT id, name, description, created_at
FROM channels
ORDER BY name
`

func (q *Queries) GetAllChannels(ctx context.Context) ([]*Channel, error) {
	rows, err := q.db.Query(ctx, getAllChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAlerts = `-- name: GetUserAlerts :many
SELECT
    a.id, a.user_id, a.metric, a.operator, a.value, a.ca, a.repeatable, a.status, a.updated_at, a.created_at,
    COALESCE(
        json_agg(
            json_build_object(
                'id', c.id,
                'name', c.name,
                'description', c.description
            )
        ) FILTER (WHERE c.id IS NOT NULL),
        '[]'
    ) AS channels
FROM alerts a
LEFT JOIN alert_channels ac ON a.id = ac.alert_id
LEFT JOIN channels c ON ac.channel_id = c.id
WHERE a.user_id = $1
GROUP BY a.id
ORDER BY a.created_at DESC
`

type GetUserAlertsRow struct {
	ID         uuid.UUID `json:"id"`
	UserID     string    `json:"userId"`
	Metric     string    `binding:"required" json:"metric"`
	Operator   string    `binding:"required" json:"operator"`
	Value      string    `binding:"required" json:"value"`
	Ca         string    `binding:"required" example:"SP1Y5YSTAHZ88XYK1VPDH24GY0HPX5J4JECTMY4A1.velar-token" json:"ca"`
	Repeatable bool      `binding:"required" json:"repeatable"`
	Status     string    `binding:"required" json:"status"`
	UpdatedAt  time.Time `json:"updatedAt"`
	CreatedAt  time.Time `json:"createdAt"`
	Channels   []byte    `json:"channels"`
}

// returns: id:uuid, user_id:string, metric:string, operator:string, value:string, ca:string, repeatable:bool, status:string, updated_at:timestamp, created_at:timestamp, channels:[]Channel
func (q *Queries) GetUserAlerts(ctx context.Context, userID string) ([]*GetUserAlertsRow, error) {
	rows, err := q.db.Query(ctx, getUserAlerts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetUserAlertsRow
	for rows.Next() {
		var i GetUserAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Metric,
			&i.Operator,
			&i.Value,
			&i.Ca,
			&i.Repeatable,
			&i.Status,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Channels,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasAlert = `-- name: HasAlert :one
SELECT EXISTS (
    SELECT 1 FROM alerts
    WHERE id = $1 AND user_id = $2
)
`

type HasAlertParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"userId"`
}

func (q *Queries) HasAlert(ctx context.Context, arg HasAlertParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAlert, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAlertChannels = `-- name: InsertAlertChannels :many
INSERT INTO alert_channels (alert_id, channel_id)
SELECT $1, UNNEST($2::uuid[])
RETURNING channel_id
`

type InsertAlertChannelsParams struct {
	AlertID uuid.UUID   `json:"alertId"`
	Column2 []uuid.UUID `json:"column2"`
}

func (q *Queries) InsertAlertChannels(ctx context.Context, arg InsertAlertChannelsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, insertAlertChannels, arg.AlertID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var channel_id uuid.UUID
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceAlertChannels = `-- name: ReplaceAlertChannels :one
WITH deleted AS (
  DELETE FROM alert_channels
  WHERE alert_id = $1
),
inserted AS (
  INSERT INTO alert_channels (alert_id, channel_id)
  SELECT $1, UNNEST($2::uuid[])
  RETURNING channel_id
)
SELECT COALESCE(
  json_agg(json_build_object('id', i.channel_id)) FILTER (WHERE i.channel_id IS NOT NULL),
  '[]'
) AS channels
FROM inserted i
`

type ReplaceAlertChannelsParams struct {
	Column1 pgtype.UUID `json:"column1"`
	Column2 []uuid.UUID `json:"column2"`
}

func (q *Queries) ReplaceAlertChannels(ctx context.Context, arg ReplaceAlertChannelsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, replaceAlertChannels, arg.Column1, arg.Column2)
	var channels []byte
	err := row.Scan(&channels)
	return channels, err
}

const updateAlert = `-- name: UpdateAlert :one
UPDATE alerts
SET
    metric     = COALESCE($1, metric),
    operator   = COALESCE($2, operator),
    value      = COALESCE($3, value),
    repeatable = COALESCE($4, repeatable),
    updated_at = now()
WHERE id = $5 AND user_id = $6
RETURNING id, user_id, metric, operator, value, ca, repeatable, status, updated_at, created_at
`

type UpdateAlertParams struct {
	Metric     string    `binding:"required" json:"metric"`
	Operator   string    `binding:"required" json:"operator"`
	Value      string    `binding:"required" json:"value"`
	Repeatable bool      `binding:"required" json:"repeatable"`
	ID         uuid.UUID `json:"id"`
	UserID     string    `json:"userId"`
}

func (q *Queries) UpdateAlert(ctx context.Context, arg UpdateAlertParams) (*Alert, error) {
	row := q.db.QueryRow(ctx, updateAlert,
		arg.Metric,
		arg.Operator,
		arg.Value,
		arg.Repeatable,
		arg.ID,
		arg.UserID,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.Operator,
		&i.Value,
		&i.Ca,
		&i.Repeatable,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const updateAlertWithChannels = `-- name: UpdateAlertWithChannels :one
WITH updated AS (
  UPDATE alerts
  SET
    metric     = COALESCE($1, metric),
    operator   = COALESCE($2, operator),
    value      = COALESCE($3, value),
    repeatable = COALESCE($4, repeatable),
    updated_at = now()
  WHERE id = $5
    AND user_id = $6
  RETURNING id, user_id, metric, operator, value, repeatable, status, ca, created_at, updated_at
),
deleted AS (
  DELETE FROM alert_channels
  WHERE alert_id IN (SELECT id FROM updated)
),
inserted AS (
  INSERT INTO alert_channels (alert_id, channel_id)
  SELECT u.id, UNNEST($7::uuid[])
  FROM updated u
  ON CONFLICT DO NOTHING
  RETURNING 1
)
SELECT
  u.id,
  u.user_id,
  u.metric,
  u.operator,
  u.value,
  u.repeatable,
  u.status,
  u.ca,
  u.created_at,
  u.updated_at,
  COALESCE(
    json_agg(json_build_object('id', ac.channel_id))
    FILTER (WHERE ac.channel_id IS NOT NULL),
    '[]'
  ) AS channels
FROM updated u
LEFT JOIN alert_channels ac ON ac.alert_id = u.id
JOIN inserted i ON TRUE
GROUP BY
  u.id,
  u.user_id,
  u.metric,
  u.operator,
  u.value,
  u.repeatable,
  u.status,
  u.ca,
  u.created_at,
  u.updated_at
`

type UpdateAlertWithChannelsParams struct {
	Metric     *string     `json:"metric"`
	Operator   *string     `json:"operator"`
	Value      *string     `json:"value"`
	Repeatable *bool       `json:"repeatable"`
	AlertID    pgtype.UUID `json:"alertId"`
	UserID     *string     `json:"userId"`
	ChannelIds []uuid.UUID `json:"channelIds"`
}

type UpdateAlertWithChannelsRow struct {
	ID         uuid.UUID `json:"id"`
	UserID     string    `json:"userId"`
	Metric     string    `json:"metric"`
	Operator   string    `json:"operator"`
	Value      string    `json:"value"`
	Repeatable bool      `json:"repeatable"`
	Status     string    `json:"status"`
	Ca         string    `json:"ca"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
	Channels   []byte    `json:"channels"`
}

// 👇 force dependency on inserted
func (q *Queries) UpdateAlertWithChannels(ctx context.Context, arg UpdateAlertWithChannelsParams) (*UpdateAlertWithChannelsRow, error) {
	row := q.db.QueryRow(ctx, updateAlertWithChannels,
		arg.Metric,
		arg.Operator,
		arg.Value,
		arg.Repeatable,
		arg.AlertID,
		arg.UserID,
		arg.ChannelIds,
	)
	var i UpdateAlertWithChannelsRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.Operator,
		&i.Value,
		&i.Repeatable,
		&i.Status,
		&i.Ca,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Channels,
	)
	return &i, err
}
