// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hodlmm_alerts.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHodlmmAlerts = `-- name: CreateHodlmmAlerts :many
INSERT INTO hodlmm_alerts (
  user_id,
  stacks_address,
  pool_id,
  pool_contract,
  display_name,
  token_x_symbol,
  token_y_symbol,
  notify_via_webapp,
  notify_via_telegram,
  notify_via_email,
  notify_via_webhook,
  notify_on_out_of_range,
  notify_on_back_in_range,
  last_known_status,
  status
)
SELECT
  $1,
  unnest($2::text[]),
  unnest($3::text[]),
  unnest($4::text[]),
  unnest($5::text[]),
  unnest($6::text[]),
  unnest($7::text[]),
  unnest($8::boolean[]),
  unnest($9::boolean[]),
  unnest($10::boolean[]),
  unnest($11::boolean[]),
  unnest($12::boolean[]),
  unnest($13::boolean[]),
  unnest($14::text[]),
  'active'
RETURNING id, user_id, stacks_address, pool_id, pool_contract, display_name, token_x_symbol, token_y_symbol, notify_via_webapp, notify_via_telegram, notify_via_email, notify_via_webhook, notify_on_out_of_range, notify_on_back_in_range, last_known_status, last_known_value_usd, last_checked, last_notified, status, created_at, updated_at
`

type CreateHodlmmAlertsParams struct {
	UserID                   string   `json:"userId"`
	StacksAddresses          []string `json:"stacksAddresses"`
	PoolIds                  []string `json:"poolIds"`
	PoolContracts            []string `json:"poolContracts"`
	DisplayNames             []string `json:"displayNames"`
	TokenXSymbols            []string `json:"tokenXSymbols"`
	TokenYSymbols            []string `json:"tokenYSymbols"`
	NotifyViaWebappFlags     []bool   `json:"notifyViaWebappFlags"`
	NotifyViaTelegramFlags   []bool   `json:"notifyViaTelegramFlags"`
	NotifyViaEmailFlags      []bool   `json:"notifyViaEmailFlags"`
	NotifyViaWebhookFlags    []bool   `json:"notifyViaWebhookFlags"`
	NotifyOnOutOfRangeFlags  []bool   `json:"notifyOnOutOfRangeFlags"`
	NotifyOnBackInRangeFlags []bool   `json:"notifyOnBackInRangeFlags"`
	InitialStatuses          []string `json:"initialStatuses"`
}

func (q *Queries) CreateHodlmmAlerts(ctx context.Context, arg CreateHodlmmAlertsParams) ([]*HodlmmAlert, error) {
	rows, err := q.db.Query(ctx, createHodlmmAlerts,
		arg.UserID,
		arg.StacksAddresses,
		arg.PoolIds,
		arg.PoolContracts,
		arg.DisplayNames,
		arg.TokenXSymbols,
		arg.TokenYSymbols,
		arg.NotifyViaWebappFlags,
		arg.NotifyViaTelegramFlags,
		arg.NotifyViaEmailFlags,
		arg.NotifyViaWebhookFlags,
		arg.NotifyOnOutOfRangeFlags,
		arg.NotifyOnBackInRangeFlags,
		arg.InitialStatuses,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*HodlmmAlert
	for rows.Next() {
		var i HodlmmAlert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StacksAddress,
			&i.PoolID,
			&i.PoolContract,
			&i.DisplayName,
			&i.TokenXSymbol,
			&i.TokenYSymbol,
			&i.NotifyViaWebapp,
			&i.NotifyViaTelegram,
			&i.NotifyViaEmail,
			&i.NotifyViaWebhook,
			&i.NotifyOnOutOfRange,
			&i.NotifyOnBackInRange,
			&i.LastKnownStatus,
			&i.LastKnownValueUsd,
			&i.LastChecked,
			&i.LastNotified,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteHodlmmAlert = `-- name: DeleteHodlmmAlert :exec
DELETE FROM hodlmm_alerts
WHERE id = $1 AND user_id = $2
`

type DeleteHodlmmAlertParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"userId"`
}

func (q *Queries) DeleteHodlmmAlert(ctx context.Context, arg DeleteHodlmmAlertParams) error {
	_, err := q.db.Exec(ctx, deleteHodlmmAlert, arg.ID, arg.UserID)
	return err
}

const getHodlmmAlertByID = `-- name: GetHodlmmAlertByID :one
SELECT id, user_id, stacks_address, pool_id, pool_contract, display_name, token_x_symbol, token_y_symbol, notify_via_webapp, notify_via_telegram, notify_via_email, notify_via_webhook, notify_on_out_of_range, notify_on_back_in_range, last_known_status, last_known_value_usd, last_checked, last_notified, status, created_at, updated_at FROM hodlmm_alerts
WHERE id = $1 AND user_id = $2
`

type GetHodlmmAlertByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"userId"`
}

func (q *Queries) GetHodlmmAlertByID(ctx context.Context, arg GetHodlmmAlertByIDParams) (*HodlmmAlert, error) {
	row := q.db.QueryRow(ctx, getHodlmmAlertByID, arg.ID, arg.UserID)
	var i HodlmmAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StacksAddress,
		&i.PoolID,
		&i.PoolContract,
		&i.DisplayName,
		&i.TokenXSymbol,
		&i.TokenYSymbol,
		&i.NotifyViaWebapp,
		&i.NotifyViaTelegram,
		&i.NotifyViaEmail,
		&i.NotifyViaWebhook,
		&i.NotifyOnOutOfRange,
		&i.NotifyOnBackInRange,
		&i.LastKnownStatus,
		&i.LastKnownValueUsd,
		&i.LastChecked,
		&i.LastNotified,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getHodlmmAlerts = `-- name: GetHodlmmAlerts :many
SELECT id, user_id, stacks_address, pool_id, pool_contract, display_name, token_x_symbol, token_y_symbol, notify_via_webapp, notify_via_telegram, notify_via_email, notify_via_webhook, notify_on_out_of_range, notify_on_back_in_range, last_known_status, last_known_value_usd, last_checked, last_notified, status, created_at, updated_at FROM hodlmm_alerts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetHodlmmAlerts(ctx context.Context, userID string) ([]*HodlmmAlert, error) {
	rows, err := q.db.Query(ctx, getHodlmmAlerts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*HodlmmAlert
	for rows.Next() {
		var i HodlmmAlert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StacksAddress,
			&i.PoolID,
			&i.PoolContract,
			&i.DisplayName,
			&i.TokenXSymbol,
			&i.TokenYSymbol,
			&i.NotifyViaWebapp,
			&i.NotifyViaTelegram,
			&i.NotifyViaEmail,
			&i.NotifyViaWebhook,
			&i.NotifyOnOutOfRange,
			&i.NotifyOnBackInRange,
			&i.LastKnownStatus,
			&i.LastKnownValueUsd,
			&i.LastChecked,
			&i.LastNotified,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseAllHodlmmAlerts = `-- name: PauseAllHodlmmAlerts :exec
UPDATE hodlmm_alerts
SET status = 'paused', updated_at = NOW()
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) PauseAllHodlmmAlerts(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, pauseAllHodlmmAlerts, userID)
	return err
}

const updateHodlmmAlert = `-- name: UpdateHodlmmAlert :one
UPDATE hodlmm_alerts
SET
  notify_via_webapp = COALESCE($1, notify_via_webapp),
  notify_via_telegram = COALESCE($2, notify_via_telegram),
  notify_via_email = COALESCE($3, notify_via_email),
  notify_via_webhook = COALESCE($4, notify_via_webhook),
  notify_on_out_of_range = COALESCE($5, notify_on_out_of_range),
  notify_on_back_in_range = COALESCE($6, notify_on_back_in_range),
  status = COALESCE($7, status),
  updated_at = NOW()
WHERE id = $8 AND user_id = $9
RETURNING id, user_id, stacks_address, pool_id, pool_contract, display_name, token_x_symbol, token_y_symbol, notify_via_webapp, notify_via_telegram, notify_via_email, notify_via_webhook, notify_on_out_of_range, notify_on_back_in_range, last_known_status, last_known_value_usd, last_checked, last_notified, status, created_at, updated_at
`

type UpdateHodlmmAlertParams struct {
	NotifyViaWebapp     *bool     `json:"notifyViaWebapp"`
	NotifyViaTelegram   *bool     `json:"notifyViaTelegram"`
	NotifyViaEmail      *bool     `json:"notifyViaEmail"`
	NotifyViaWebhook    *bool     `json:"notifyViaWebhook"`
	NotifyOnOutOfRange  *bool     `json:"notifyOnOutOfRange"`
	NotifyOnBackInRange *bool     `json:"notifyOnBackInRange"`
	Status              *string   `json:"status"`
	ID                  uuid.UUID `json:"id"`
	UserID              string    `json:"userId"`
}

func (q *Queries) UpdateHodlmmAlert(ctx context.Context, arg UpdateHodlmmAlertParams) (*HodlmmAlert, error) {
	row := q.db.QueryRow(ctx, updateHodlmmAlert,
		arg.NotifyViaWebapp,
		arg.NotifyViaTelegram,
		arg.NotifyViaEmail,
		arg.NotifyViaWebhook,
		arg.NotifyOnOutOfRange,
		arg.NotifyOnBackInRange,
		arg.Status,
		arg.ID,
		arg.UserID,
	)
	var i HodlmmAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StacksAddress,
		&i.PoolID,
		&i.PoolContract,
		&i.DisplayName,
		&i.TokenXSymbol,
		&i.TokenYSymbol,
		&i.NotifyViaWebapp,
		&i.NotifyViaTelegram,
		&i.NotifyViaEmail,
		&i.NotifyViaWebhook,
		&i.NotifyOnOutOfRange,
		&i.NotifyOnBackInRange,
		&i.LastKnownStatus,
		&i.LastKnownValueUsd,
		&i.LastChecked,
		&i.LastNotified,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateHodlmmAlertStatus = `-- name: UpdateHodlmmAlertStatus :one
UPDATE hodlmm_alerts
SET
  last_known_status = $2,
  last_known_value_usd = $3,
  last_checked = NOW(),
  updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, stacks_address, pool_id, pool_contract, display_name, token_x_symbol, token_y_symbol, notify_via_webapp, notify_via_telegram, notify_via_email, notify_via_webhook, notify_on_out_of_range, notify_on_back_in_range, last_known_status, last_known_value_usd, last_checked, last_notified, status, created_at, updated_at
`

type UpdateHodlmmAlertStatusParams struct {
	ID                uuid.UUID      `json:"id"`
	LastKnownStatus   string         `json:"lastKnownStatus"`
	LastKnownValueUsd pgtype.Numeric `json:"lastKnownValueUsd"`
}

func (q *Queries) UpdateHodlmmAlertStatus(ctx context.Context, arg UpdateHodlmmAlertStatusParams) (*HodlmmAlert, error) {
	row := q.db.QueryRow(ctx, updateHodlmmAlertStatus, arg.ID, arg.LastKnownStatus, arg.LastKnownValueUsd)
	var i HodlmmAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StacksAddress,
		&i.PoolID,
		&i.PoolContract,
		&i.DisplayName,
		&i.TokenXSymbol,
		&i.TokenYSymbol,
		&i.NotifyViaWebapp,
		&i.NotifyViaTelegram,
		&i.NotifyViaEmail,
		&i.NotifyViaWebhook,
		&i.NotifyOnOutOfRange,
		&i.NotifyOnBackInRange,
		&i.LastKnownStatus,
		&i.LastKnownValueUsd,
		&i.LastChecked,
		&i.LastNotified,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
