// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CleanupOrphanedWallet(ctx context.Context, address string) error
	CreateAlert(ctx context.Context, arg CreateAlertParams) (*Alert, error)
	CreateAlertChannel(ctx context.Context, arg CreateAlertChannelParams) error
	CreateAlertChannels(ctx context.Context, arg CreateAlertChannelsParams) error
	CreateTelegramUser(ctx context.Context, arg CreateTelegramUserParams) (*TelegramUser, error)
	CreateWallet(ctx context.Context, address string) (*CreateWalletRow, error)
	CreateWatchlist(ctx context.Context, arg CreateWatchlistParams) (*Watchlist, error)
	CreateWebhookConfig(ctx context.Context, arg CreateWebhookConfigParams) (*WebhookConfig, error)
	DeleteAlert(ctx context.Context, arg DeleteAlertParams) (*Alert, error)
	DeleteAlertChannels(ctx context.Context, alertID uuid.UUID) error
	DeleteAlerts(ctx context.Context, arg DeleteAlertsParams) ([]*Alert, error)
	DeleteAllInactiveAlerts(ctx context.Context, userID string) error
	DeleteWatchlist(ctx context.Context, arg DeleteWatchlistParams) error
	DeleteWebhookConfig(ctx context.Context, userID string) error
	GetActiveAlertsByMetric(ctx context.Context, metric string) ([]*Alert, error)
	GetAlertById(ctx context.Context, arg GetAlertByIdParams) (*Alert, error)
	GetAllChannels(ctx context.Context) ([]*Channel, error)
	GetAllWallets(ctx context.Context) ([]*Wallet, error)
	GetAllWalletsAndWatchers(ctx context.Context) ([]*GetAllWalletsAndWatchersRow, error)
	GetTelegramUser(ctx context.Context, chatID string) (*TelegramUser, error)
	GetTrackedWalletsTelegram(ctx context.Context, chatID string) ([]*GetTrackedWalletsTelegramRow, error)
	// returns: id:uuid, user_id:string, metric:string, operator:string, value:string, ca:string, repeatable:bool, status:string, updated_at:timestamp, created_at:timestamp, channels:[]Channel
	GetUserAlerts(ctx context.Context, userID string) ([]*GetUserAlertsRow, error)
	GetUserByEmail(ctx context.Context, email *string) (*User, error)
	GetUserById(ctx context.Context, id string) (*User, error)
	GetUserTrackedWallets(ctx context.Context, userID string) ([]*GetUserTrackedWalletsRow, error)
	GetUserWalletDetails(ctx context.Context, arg GetUserWalletDetailsParams) (*GetUserWalletDetailsRow, error)
	GetWalletsWithWatchers(ctx context.Context) ([]*GetWalletsWithWatchersRow, error)
	GetWatchersForWallet(ctx context.Context, walletAddress string) ([]*GetWatchersForWalletRow, error)
	GetWatchlistsByUserId(ctx context.Context, userID *string) ([]*Watchlist, error)
	GetWebhookConfigByUserID(ctx context.Context, userID string) (*WebhookConfig, error)
	HasAlert(ctx context.Context, arg HasAlertParams) (bool, error)
	HasWatchlist(ctx context.Context, arg HasWatchlistParams) (bool, error)
	HasWatchlistById(ctx context.Context, arg HasWatchlistByIdParams) (bool, error)
	InsertAlertChannels(ctx context.Context, arg InsertAlertChannelsParams) ([]uuid.UUID, error)
	IsTrackingWallet(ctx context.Context, arg IsTrackingWalletParams) (bool, error)
	IsTrackingWalletTelegram(ctx context.Context, arg IsTrackingWalletTelegramParams) (bool, error)
	ReplaceAlertChannels(ctx context.Context, arg ReplaceAlertChannelsParams) ([]byte, error)
	TrackWalletTelegram(ctx context.Context, arg TrackWalletTelegramParams) (*TelegramUserWallet, error)
	UntrackWallet(ctx context.Context, arg UntrackWalletParams) error
	UntrackWalletTelegram(ctx context.Context, arg UntrackWalletTelegramParams) error
	UpdateAlert(ctx context.Context, arg UpdateAlertParams) (*Alert, error)
	UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) (*Alert, error)
	// 👇 force dependency on inserted
	UpdateAlertWithChannels(ctx context.Context, arg UpdateAlertWithChannelsParams) (*UpdateAlertWithChannelsRow, error)
	UpdateTelegramUserPreference(ctx context.Context, arg UpdateTelegramUserPreferenceParams) (*TelegramUser, error)
	UpdateWalletPreferences(ctx context.Context, arg UpdateWalletPreferencesParams) (*UserWallet, error)
	UpdateWebhookConfig(ctx context.Context, arg UpdateWebhookConfigParams) (*WebhookConfig, error)
	UpdateWebhookConfigStatus(ctx context.Context, arg UpdateWebhookConfigStatusParams) (*WebhookConfig, error)
	UpsertTelegramUserWallet(ctx context.Context, arg UpsertTelegramUserWalletParams) (*TelegramUserWallet, error)
	UpsertUserWallet(ctx context.Context, arg UpsertUserWalletParams) (*UserWallet, error)
	WalletExists(ctx context.Context, address string) (bool, error)
}

var _ Querier = (*Queries)(nil)
