// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRefreshTokenID(ctx context.Context, arg AddRefreshTokenIDParams) (*RefreshToken, error)
	DeleteRefreshToken(ctx context.Context, id uuid.UUID) error
	GetRefreshTokenUserID(ctx context.Context, id uuid.UUID) (pgtype.UUID, error)
	GetUserByEmail(ctx context.Context, email *string) (*User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (*User, error)
	RefreshTokenExists(ctx context.Context, id uuid.UUID) (bool, error)
	RegisterTelegramUser(ctx context.Context, arg RegisterTelegramUserParams) (*User, error)
	RegisterUser(ctx context.Context, arg RegisterUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
