// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: watchlist.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createWatchlist = `-- name: CreateWatchlist :one
INSERT INTO watchlists (
    ca, user_id
) VALUES (
    $1, $2
)
RETURNING id, ca, user_id, updated_at, created_at
`

type CreateWatchlistParams struct {
	Ca     string    `binding:"required" example:"SP1Y5YSTAHZ88XYK1VPDH24GY0HPX5J4JECTMY4A1.velar-token" json:"ca"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) CreateWatchlist(ctx context.Context, arg CreateWatchlistParams) (*Watchlist, error) {
	row := q.db.QueryRow(ctx, createWatchlist, arg.Ca, arg.UserID)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.Ca,
		&i.UserID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteWatchlist = `-- name: DeleteWatchlist :exec
DELETE FROM watchlists
WHERE id = $1
`

func (q *Queries) DeleteWatchlist(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWatchlist, id)
	return err
}

const deleteWatchlistsByUserId = `-- name: DeleteWatchlistsByUserId :exec
DELETE FROM watchlists
WHERE user_id = $1
`

func (q *Queries) DeleteWatchlistsByUserId(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWatchlistsByUserId, userID)
	return err
}

const getWatchlistById = `-- name: GetWatchlistById :one
SELECT id, ca, user_id, updated_at, created_at FROM watchlists
WHERE id = $1
`

func (q *Queries) GetWatchlistById(ctx context.Context, id uuid.UUID) (*Watchlist, error) {
	row := q.db.QueryRow(ctx, getWatchlistById, id)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.Ca,
		&i.UserID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getWatchlistByUserIdAndCA = `-- name: GetWatchlistByUserIdAndCA :one
SELECT id, ca, user_id, updated_at, created_at FROM watchlists
WHERE user_id = $1 AND ca = $2
`

type GetWatchlistByUserIdAndCAParams struct {
	UserID uuid.UUID `json:"userId"`
	Ca     string    `binding:"required" example:"SP1Y5YSTAHZ88XYK1VPDH24GY0HPX5J4JECTMY4A1.velar-token" json:"ca"`
}

func (q *Queries) GetWatchlistByUserIdAndCA(ctx context.Context, arg GetWatchlistByUserIdAndCAParams) (*Watchlist, error) {
	row := q.db.QueryRow(ctx, getWatchlistByUserIdAndCA, arg.UserID, arg.Ca)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.Ca,
		&i.UserID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getWatchlistsByUserId = `-- name: GetWatchlistsByUserId :many
SELECT id, ca, user_id, updated_at, created_at FROM watchlists
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetWatchlistsByUserId(ctx context.Context, userID uuid.UUID) ([]*Watchlist, error) {
	rows, err := q.db.Query(ctx, getWatchlistsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Watchlist
	for rows.Next() {
		var i Watchlist
		if err := rows.Scan(
			&i.ID,
			&i.Ca,
			&i.UserID,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWatchlist = `-- name: UpdateWatchlist :one
UPDATE watchlists
SET ca = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, ca, user_id, updated_at, created_at
`

type UpdateWatchlistParams struct {
	ID uuid.UUID `json:"id"`
	Ca string    `binding:"required" example:"SP1Y5YSTAHZ88XYK1VPDH24GY0HPX5J4JECTMY4A1.velar-token" json:"ca"`
}

func (q *Queries) UpdateWatchlist(ctx context.Context, arg UpdateWatchlistParams) (*Watchlist, error) {
	row := q.db.QueryRow(ctx, updateWatchlist, arg.ID, arg.Ca)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.Ca,
		&i.UserID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}
