// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook.sql

package repository

import (
	"context"
)

const createWebhookConfig = `-- name: CreateWebhookConfig :one
INSERT INTO webhook_config (
    user_id, webhook_url, bearer_token, enabled, status
) VALUES (
    $1, $2, $3, true, 'streaming'
)
RETURNING id, user_id, webhook_url, bearer_token, enabled, status, updated_at, created_at
`

type CreateWebhookConfigParams struct {
	UserID      string `json:"userId"`
	WebhookUrl  string `json:"webhookUrl"`
	BearerToken string `json:"bearerToken"`
}

func (q *Queries) CreateWebhookConfig(ctx context.Context, arg CreateWebhookConfigParams) (*WebhookConfig, error) {
	row := q.db.QueryRow(ctx, createWebhookConfig, arg.UserID, arg.WebhookUrl, arg.BearerToken)
	var i WebhookConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WebhookUrl,
		&i.BearerToken,
		&i.Enabled,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteWebhookConfig = `-- name: DeleteWebhookConfig :exec
DELETE FROM webhook_config
WHERE user_id = $1
`

func (q *Queries) DeleteWebhookConfig(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteWebhookConfig, userID)
	return err
}

const getWebhookConfigByUserID = `-- name: GetWebhookConfigByUserID :one
SELECT id, user_id, webhook_url, bearer_token, enabled, status, updated_at, created_at FROM webhook_config
WHERE user_id = $1
`

func (q *Queries) GetWebhookConfigByUserID(ctx context.Context, userID string) (*WebhookConfig, error) {
	row := q.db.QueryRow(ctx, getWebhookConfigByUserID, userID)
	var i WebhookConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WebhookUrl,
		&i.BearerToken,
		&i.Enabled,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const updateWebhookConfig = `-- name: UpdateWebhookConfig :one
UPDATE webhook_config
SET
    webhook_url = COALESCE($1, webhook_url),
    bearer_token = COALESCE($2, bearer_token),
    enabled = COALESCE($3, enabled),
    updated_at = now()
WHERE user_id = $4
RETURNING id, user_id, webhook_url, bearer_token, enabled, status, updated_at, created_at
`

type UpdateWebhookConfigParams struct {
	WebhookUrl  string `json:"webhookUrl"`
	BearerToken string `json:"bearerToken"`
	Enabled     *bool  `json:"enabled"`
	UserID      string `json:"userId"`
}

func (q *Queries) UpdateWebhookConfig(ctx context.Context, arg UpdateWebhookConfigParams) (*WebhookConfig, error) {
	row := q.db.QueryRow(ctx, updateWebhookConfig,
		arg.WebhookUrl,
		arg.BearerToken,
		arg.Enabled,
		arg.UserID,
	)
	var i WebhookConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WebhookUrl,
		&i.BearerToken,
		&i.Enabled,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const updateWebhookConfigStatus = `-- name: UpdateWebhookConfigStatus :one
UPDATE webhook_config
SET
    status = COALESCE($1, status),
    updated_at = now()
WHERE user_id = $2
RETURNING id, user_id, webhook_url, bearer_token, enabled, status, updated_at, created_at
`

type UpdateWebhookConfigStatusParams struct {
	Status string `json:"status"`
	UserID string `json:"userId"`
}

func (q *Queries) UpdateWebhookConfigStatus(ctx context.Context, arg UpdateWebhookConfigStatusParams) (*WebhookConfig, error) {
	row := q.db.QueryRow(ctx, updateWebhookConfigStatus, arg.Status, arg.UserID)
	var i WebhookConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WebhookUrl,
		&i.BearerToken,
		&i.Enabled,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return &i, err
}
